services:
  app1:
    build:
      context: .
      args:
        - BACKGROUND_COLOR=#ffacac
        - APP_NAME=First service
  app2:
    build:
      context: .
      args:
        - APP_NAME=Second service
        - BACKGROUND_COLOR=#b0dcac
  app3:
    build:
      context: .
      args:
        - APP_NAME=Third service
        - BACKGROUND_COLOR=#50dcdc
  server1:
    image: nginx
    volumes:
      - ./etc/loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4200:8080
    depends_on:
      - app1
      - app2
      - app3
  server2:
    image: nginx
    volumes:
      - ./etc/weighed-loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4201:8080
    depends_on:
      - app1
      - app2
      - app3