services:
  app1:
    build:
      context: .
      args:
        - BACKGROUND_COLOR=red
        - APP_NAME=First service
    networks:
      - front-tier
    depends_on:
      redis:
        condition: service_healthy
  app2:
    build:
      context: .
      args:
        - APP_NAME=Second service
        - BACKGROUND_COLOR=black
    networks:
      - front-tier
    depends_on:
      redis:
        condition: service_healthy
  app3:
    build:
      context: .
      args:
        - APP_NAME=Third service
        - BACKGROUND_COLOR=blue
    networks:
      - front-tier
    depends_on:
      redis:
        condition: service_healthy
  server:
    image: nginx:latest
    volumes:
      - ./etc/loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4210:8080
    networks:
      - front-tier
      - back-tier
    depends_on:
      - app1
      - app2
      - app3

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    networks:
      - back-tier
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

      
networks:
  front-tier: {}
  back-tier: {}
