services:
  backend:
    build:
      context: .
    image: spring-redis-backend
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
